logging.level.org.springframework: INFO
server.port: 80
spring:
  datasource:
    url: jdbc:mysql://anigiri-db:3306/anigiri_db?autoReconnect=true&useSSL=false
    username: anigiri
    password: password
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
